/* Headers - Declarations - Definitions*/
%{
#include<stdio.h>

int yylex();                /* It is the function generated by Flex. */
void yyerror(const char*);  

%}

/* Define tokens */

%union {
    int ival;
    char strval[5];
}

/*
FLEX                         BISON
produce terminals            built no terminals

NUMBER ────────────────┐
SUM ───────────────────┤
SUB ───────────────────┤
MULT ──────────────────┼───> Grammar
DIV ───────────────────┤
ABS ───────────────────┤
ENDLINE ───────────────┘
*/

/* Terminal types */
%token<ival>   NUMBER
%token<strval> SUM
%token<strval> SUB
%token<strval> MULT
%token<strval> DIV
%token<strval> ABS
%token         ENDLINE

/* No-terminals types:
This says that the non-terminal operator will have a semantic value strval and the operand will have a semantic value ival. */
%type<strval> operator
%type<ival>   operand

/* Grammar rules */
%%
input: 
    | input operand  { printf("operand = %d\n", $2); } 
    | input operator { printf("operator = %s\n", $2); }
    | input endline  { printf("endline\n"); }
    ;
operator: SUM
    |   SUB
    |   MULT
    |   DIV
    |   ABS
    ;
operand: NUMBER
    ;
endline: ENDLINE
    ;
%%


/* User function */


void yyerror(const char* mssg)
{   
    printf("penca %s\n", mssg);
}

int 
main(void)
{
    yyparse();
    /*
        yyparse()
          BISON
            |
    "give me other token"
            |
            v
          yylex()
           FLEX
            |
            v
          INPUT
            |
            |
    NUMBER / SUM / ...
            |
            v
          BISON
            |
            v
          Grammar
            |
            v
          Actions
    */

    return 0;
}