/* Headers - Declarations - Definitions*/
%{
#include<stdio.h>
#include<stdint.h>

int yylex();                /* It is the function generated by Flex. */
void yyerror(const char*);

uint32_t n_lines   = 0;
uint32_t n_words   = 0;
uint32_t n_numbers = 0;
uint32_t n_chars   = 0;
uint32_t n_spaces  = 0;
uint32_t n_others  = 0;

%}

/* Define tokens */

%union {
    int ival;
    char strval[20];
}

/* Terminal types */
%token<strval> WORD
%token<ival>   NUMBER
%token         NEWLINE
%token         SPACE
%token         OTHER

/* Grammar rules */
%%
input: 
    | input WORD     { ++n_words;   n_chars += yylen;  printf("Word = %s\n", $2);   } 
    | input NUMBER   { ++n_numbers; n_chars += yylen;  printf("Number = %d\n", $2); }
    | input NEWLINE  { ++n_lines;   ++n_chars;         printf("Newline\n");         }
    | input SPACE    { ++n_spaces;  ++n_chars;         printf("Space\n");           }
    | input OTHER    { ++n_others;  ++n_chars;         printf("Other\n");           }
    ;
%%


/* User functions */

void yyerror(const char* mssg)
{   
    printf("penca %s\n", mssg);
}

int 
main(void)
{
    yyparse();
    /*
        yyparse()
          BISON
            |
    "give me other token"
            |
            v
          yylex()
           FLEX
            |
            v
          INPUT
            |
            |
    WORD / NUMBER / ...
            |
            v
          BISON
            |
            v
          Grammar
            |
            v
          Actions
    */

    printf("Lines: %u\n", n_lines);
    printf("Words: %u\n", n_words);
    printf("Numbers: %u\n", n_numbers);
    printf("Characters: %u\n", n_chars);
    printf("Spaces: %u\n", n_spaces);
    printf("Others: %u\n", n_others);

    return 0;
}